# Collects every URL cited anywhere in data/*.json and data/raw/*.json into one bibliography.
# Output: data/all_sources.json  +  methods/SOURCES.md
$ErrorActionPreference = 'Stop'
$root = Split-Path (Split-Path $PSScriptRoot -Parent) -Parent

$found = @{}
function Walk($node, $file, $ctx) {
  if ($null -eq $node) { return }
  if ($node -is [string]) {
    foreach ($m in [regex]::Matches($node, 'https?://[^\s"''<>)\]]+')) {
      $u = $m.Value.TrimEnd('.', ',', ';')
      if (-not $found.ContainsKey($u)) { $found[$u] = [ordered]@{ url = $u; title = $ctx.title; publisher = $ctx.publisher; cited_in = New-Object System.Collections.ArrayList } }
      if (-not $found[$u].cited_in.Contains($file)) { [void]$found[$u].cited_in.Add($file) }
    }
    return
  }
  if ($node -is [System.Collections.IEnumerable] -and -not ($node -is [string])) { foreach ($i in $node) { Walk $i $file $ctx }; return }
  if ($node -is [pscustomobject]) {
    $c = @{ title = $ctx.title; publisher = $ctx.publisher }
    $props = $node.PSObject.Properties
    if ($props['title'] -and $node.title -is [string]) { $c.title = $node.title }
    if ($props['publisher'] -and $node.publisher -is [string]) { $c.publisher = $node.publisher }
    foreach ($p in $props) { Walk $p.Value $file $c }
  }
}

$files = @(Get-ChildItem "$root\data\*.json") + @(Get-ChildItem "$root\data\raw\*.json")
foreach ($f in $files) {
  $rel = $f.FullName.Substring($root.Length + 1)
  try { $j = Get-Content $f.FullName -Raw -Encoding UTF8 | ConvertFrom-Json } catch { Write-Warning "skip $rel"; continue }
  Walk $j $rel @{ title = $null; publisher = $null }
}

$list = @($found.Values | Sort-Object { ([uri]$_.url).Host }, { $_.url })
[IO.File]::WriteAllText("$root\data\all_sources.json", (ConvertTo-Json -InputObject $list -Depth 5), (New-Object Text.UTF8Encoding($false)))

$sb = New-Object Text.StringBuilder
[void]$sb.AppendLine("# All sources cited in the dataset")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("Generated by ``methods/scripts/build_sources.ps1`` on $(Get-Date -Format yyyy-MM-dd). $($list.Count) unique URLs, grouped by domain. ``cited_in`` shows which data file uses each one.")
[void]$sb.AppendLine("")
$list | Group-Object { ([uri]$_.url).Host } | Sort-Object Count -Descending | ForEach-Object {
  [void]$sb.AppendLine("## $($_.Name) ($($_.Count))")
  foreach ($s in $_.Group) {
    $t = if ($s.title) { $s.title } else { '(untitled)' }
    [void]$sb.AppendLine("- [$t]($($s.url)) - ``$(($s.cited_in) -join '``, ``')``")
  }
  [void]$sb.AppendLine("")
}
[IO.File]::WriteAllText("$root\methods\SOURCES.md", $sb.ToString(), (New-Object Text.UTF8Encoding($false)))
"unique URLs: $($list.Count); domains: $(@($list | Group-Object { ([uri]$_.url).Host }).Count)"
