# Exports the media-coding dataset (199 articles across 53 deadly SA flood events) as CSV + JSON.
# Output: data/articles/ in the repo, and a copy on the Desktop.
param([string]$Desktop = "$env:USERPROFILE\Desktop\SA_flood_articles_dataset")
$ErrorActionPreference = 'Stop'
$root = Split-Path (Split-Path $PSScriptRoot -Parent) -Parent
$data = "$root\data"; $out = "$data\articles"
New-Item -ItemType Directory -Force $out, $Desktop | Out-Null
function Load($p) { (Get-Content $p -Raw -Encoding UTF8 | ConvertFrom-Json) | ForEach-Object { $_ } }

$mp = (Get-Content "$data\media_patterns_coded.json" -Raw -Encoding UTF8 | ConvertFrom-Json)
$byId = @{}; Load "$data\floods_2016_2026.json" | ForEach-Object { $byId[$_.id] = $_ }

# 1. One row per article read
$articles = foreach ($e in $mp.events) {
  $m = $byId[$e.id]; $i = 0
  foreach ($u in @($e.urls_read)) {
    $i++
    $hostName = try { ([uri]$u).Host -replace '^www\.', '' } catch { '' }
    [pscustomobject][ordered]@{
      article_id = "$($e.id)#$i"; event_id = $e.id; event = $m.event; event_date = $m.start_date
      provinces = (@($m.provinces) -join '; '); deaths = $m.deaths; deaths_text = $m.deaths_text
      url = $u; outlet_domain = $hostName
    }
  }
}
# 2. One row per event: the P1-P6 coding with evidence
$events = foreach ($e in $mp.events) {
  $m = $byId[$e.id]
  [pscustomobject][ordered]@{
    event_id = $e.id; event = $m.event; event_date = $m.start_date; provinces = (@($m.provinces) -join '; ')
    deaths = $m.deaths; warning_issued = "$($m.warning_issued)"; alert_level = $m.alert_level; articles_read = $e.articles_read
    P1_toll_rising = "$($e.P1.value)"; P1_evidence = $e.P1.evidence; P1_url = $e.P1.url
    P2_informal_settlement = "$($e.P2.value)"; P2_type = $e.P2.mention_type; P2_evidence = $e.P2.evidence; P2_url = $e.P2.url
    P3_president_visit = "$($e.P3.value)"; P3_who = $e.P3.who; P3b_other_visit = "$($e.P3.other_visit.value)"; P3b_who = $e.P3.other_visit.who; P3_evidence = $e.P3.evidence; P3_url = $e.P3.url
    P4_officials_quoted = $e.P4.officials_quoted; P4_residents_quoted = $e.P4.residents_quoted; P4_others_quoted = $e.P4.others_quoted; P4_officials_dominate = "$($e.P4.value)"
    P5_climate_change = "$($e.P5.value)"; P5_evidence = $e.P5.evidence; P5_url = $e.P5.url
    P6_warning_mentioned = "$($e.P6.value)"; P6_evidence = $e.P6.evidence; P6_url = $e.P6.url
    coder_note = $e.coder_note
  }
}
$articles | Export-Csv "$out\articles.csv" -NoTypeInformation -Encoding UTF8
$events | Export-Csv "$out\event_coding.csv" -NoTypeInformation -Encoding UTF8
$mp.summary | Select-Object pattern, true, false, not_determinable, out_of, note | Export-Csv "$out\pattern_summary.csv" -NoTypeInformation -Encoding UTF8
@($articles | Group-Object outlet_domain | Sort-Object Count -Descending | ForEach-Object { [pscustomobject]@{ outlet_domain = $_.Name; articles = $_.Count } }) | Export-Csv "$out\articles_by_outlet.csv" -NoTypeInformation -Encoding UTF8
Copy-Item "$data\media_patterns_coded.json" "$out\media_patterns_coded.json" -Force

$readme = @"
# SA flood coverage: the article dataset

Media-framing coding of **$(@($articles).Count) article URLs** (the coders report $( ($mp.events | Measure-Object articles_read -Sum).Sum ) articles read) across **$(@($events).Count) deadly South African flood events, 2016-2026**.

| File | Contents |
|---|---|
| ``articles.csv`` | One row per article: event, date, provinces, deaths, URL, outlet |
| ``event_coding.csv`` | One row per event: patterns P1-P6 (true / false / not_determinable) with verbatim evidence + URL, and counts of officials / residents / others quoted |
| ``pattern_summary.csv`` | Totals per pattern |
| ``articles_by_outlet.csv`` | Article count per news outlet |
| ``media_patterns_coded.json`` | The full original coding, including coder notes and method |

**Patterns:**
- P1: death toll reported as rising, never final
- P2: "informal settlement" named as the cause
- P3: presidential visit (P3b: Premier / Minister / MEC)
- P4: officials quoted over residents
- P5: climate change framing
- P6: pre-event warning mentioned at all

**Method:** $($mp.method)

Values reflect the articles read: "false" means not found in that coverage. Generated by ``methods/scripts/export_articles.ps1``.
"@
[IO.File]::WriteAllText("$out\README.md", $readme, (New-Object Text.UTF8Encoding($false)))
Copy-Item "$out\*" $Desktop -Force
"articles: $(@($articles).Count)  events: $(@($events).Count)  outlets: $(@($articles | Group-Object outlet_domain).Count)"
"repo: $out"; "desktop: $Desktop"
